### ISSUE TITLE
SearchForm does not work (example below with cut and paste)

### ISSUE THREAD

**Issue by AntonMezger** [DMKEBUSINESSGMBH/typo3-mkforms#87]
All my xml files work correctly with mkforms, however an xml file with a searchform refuses to render and tells me "Leider ist ein Fehler aufgetreten). The xml file was developed with formidable and probably something has to be changed I guess.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<formidable version="2.0.477"
	xmlns:renderlet="http://formidable.typo3.ug/xmlns/2.0.477/renderlet">

	<meta>
		<name>searchform</name>
		<form formid="searchform" />
                  <debug>false</debug>
                  <codebehind name="cb" path="fileadmin/xml/cb/class.exportxls.php" />
                  <codebehind name="cb1" path="fileadmin/xml/cb/class.userfunctions.php" />
	</meta>

	<control>
		<datasource:DB name="mytable">
				<sql>
					<userobj>
						<php><![CDATA[
                              $superuser="Superuser";
                              if(in_array($superuser, $GLOBALS['TSFE']->fe_user->groupData['title'])){
                                   return 'SELECT * FROM mytable';
                              } else {                               
				return 'SELECT * FROM mytable 
					WHERE association = ' ."'" . $GLOBALS["TSFE"]->fe_user->user["username"] ."'";
                              }	
			                          ]]></php>
					</userobj>
				</sql>	
		</datasource:DB>

	</control>

	<elements>

		<renderlet:BOX name="mybrand" mode="h2">
			<html>
				<userobj>
					<php><![CDATA[
// en=0 de=2 fr=3 it=5
                                             switch ($GLOBALS['TSFE']->sys_language_uid) {
                                             case 0:
                                                 $html = "Actual user: " .  $GLOBALS["TSFE"]->fe_user->user["username"];
                                                 break;
                                             case 2:
                                                 $html = "Aktueller Benutzer: " .  $GLOBALS["TSFE"]->fe_user->user["username"];
                                                 break;
                                             case 3:
                                                 $html = "Utilisateur actuel: " .  $GLOBALS["TSFE"]->fe_user->user["username"];
                                                 break;
                                             case 5:
                                                $html = "Utente corrente: " .  $GLOBALS["TSFE"]->fe_user->user["username"];
                                                break;
                                              }
                                             return  $html;
			]]></php>
				</userobj>
			</html>
		</renderlet:BOX>

                  <renderlet:BOX name="boxMessage" mode="H1" />
	
		<renderlet:SEARCHFORM name="mysearch">
			<datasource use="mytable" />
			<childs>

                                   <template>
                                        <path>fileadmin/xml/template/form_search.html</path>
                                   </template>

				<renderlet:TEXT name="association" class="tb2">
                                             <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.association.label</label>
				</renderlet:TEXT>

				<renderlet:TEXT name="berater" class="tb2">
                                             <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.name.label</label>
				</renderlet:TEXT>

				<renderlet:TEXT name="patient" class="tb2">
                                             <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.patient.label</label>
				</renderlet:TEXT>

		                 <renderlet:LISTBOX name="year">
			           <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.year.label</label>
			          <data>
				   <items>
					<item caption="" value=""/>
					<item caption="2007" value="2007"/>
					<item caption="2008" value="2008"/>
					<item caption="2009" value="2009"/>
					<item caption="2010" value="2010"/>
					<item caption="2011" value="2011"/>
					<item caption="2012" value="2012"/>
					<item caption="2013" value="2013"/>
					<item caption="2014" value="2014"/>
					<item caption="2015" value="2015"/>
					<item caption="2016" value="2016"/>
					<item caption="2017" value="2017"/>
					<item caption="2018" value="2018"/>
					<item caption="2019" value="2019"/>
					<item caption="2020" value="2020"/>
				   </items>
			         </data>
		              </renderlet:LISTBOX>

                                 <renderlet:DATE  name="datefrom"  class="tb2" activeListable="false" >
                                        <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.datefrom.label</label>
                                        <data>
                                                 <datetime format="%d-%m-%y" locale="fr_FR"  allowmanualedition="true" displaytime="false" convertToTimestamp="false" />
                                        </data>
                                </renderlet:DATE> 

                                <renderlet:DATE  name="dateto"  class="tb2" activeListable="false" >
                                        <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.dateto.label</label>
                                        <data>
                                                 <datetime format="%d-%m-%y" locale="fr_FR"  allowmanualedition="true" displaytime="false" convertToTimestamp="false" />
                                        </data>
                               </renderlet:DATE> 

		<renderlet:BUTTON name="exportexcel1">
                           <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.export1.label</label>
			<onclick runat="server" exec="cb.doExport()"  params="1" when="before-render"/>
		</renderlet:BUTTON>

		<renderlet:BUTTON name="exportexcel2">
                           <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.export2.label</label>
			<onclick runat="server" exec="cb.doExport()"  params="2" when="before-render"/>
		</renderlet:BUTTON>

		<renderlet:BUTTON name="print">
                           <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.pdf.label</label>
			<onclick runat="server" exec="cb.doPrint()"  when="before-render"/>
		</renderlet:BUTTON>

		<renderlet:BUTTON name="btnClear" >
                          <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.resetform.label</label>
					<onclick runat="client">
						<userobj>
							<php><![CDATA[
								
	                                                       $aTasks = array();
	                                                       $aTasks[] = $this->aORenderlets["mysearch"]->aChilds["datefrom"]->majixClearValue();
                                                                $aTasks[] = $this->aORenderlets["mysearch"]->aChilds["dateto"]->majixClearValue();
                                                                $aTasks[] = $this->aORenderlets["mysearch"]->aChilds["year"]->majixClearValue();
                                                                $aTasks[] = $this->aORenderlets["mysearch"]->aChilds["patient"]->majixClearValue();
                                                                $aTasks[] = $this->aORenderlets["mysearch"]->aChilds["association"]->majixClearValue();
                                                                $aTasks[] = $this->aORenderlets["mysearch"]->aChilds["berater"]->majixClearValue();
	                                                        return $aTasks;

							]]></php>
						</userobj>
					</onclick>
				</renderlet:BUTTON>

                  <renderlet:SUBMIT name="btnSearch" mode="search" >
                       <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.search.label</label>
                  </renderlet:SUBMIT>

			</childs>
		</renderlet:SEARCHFORM>

		<renderlet:LISTER name="pages" ajaxLister="true">
			<ifEmpty>Empty</ifEmpty>
			<searchform use="mysearch" />
			<pager>
				<rows perpage="10" />
                                     <sort column="uid"  direction="DESC"/>
			</pager>
			<columns>
				<column type="renderlet:LINK" name="uid" listHeader="id" >
					<url>
						<userobj>
							<php><![CDATA[
                                                                   return "index.php?id=80&uid=".$this->getListData('uid')."&L=".$GLOBALS['TSFE']->sys_language_uid;
							]]></php>
						</userobj>
					</url>
                                    </column>
				<column type="renderlet:TEXT" name="association" listHeader="LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.association.label" />
				<column type="renderlet:TEXT" name="berater"  listHeader="LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.name.label"/>
				<column type="renderlet:LISTBOX" name="zielerreichung" listHeader="LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.ziel.label">
					<data>
						<items>
                                                     <item><value>-1</value>
                                                         <caption>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.ziel.data.items0</caption>
                                                     </item>
                                                     <item><value>1</value>
                                                         <caption>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.ziel.data.items1</caption>
                                                     </item>
                                                     <item><value>2</value>
                                                         <caption>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.ziel.data.items2</caption>
                                                     </item>
                                                     <item><value>3</value>
                                                         <caption>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.ziel.data.items3</caption>
                                                     </item>
                                                     <item><value>4</value>
                                                         <caption>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.ziel.data.items4</caption>
                                                      </item>
                                                      <item><value>5</value>
                                                          <caption>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.ziel.data.items5</caption>
                                                      </item>
                                                       </items>
					</data>
				</column>
                                    <column type="renderlet:TEXTAREA" defaultWrap="false" name="Text"  listHeader="Text"/>
                                    <column type="renderlet:TEXT" name="year" listHeader="LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.year.label" />
                                    <column type="renderlet:TEXT" name="patient" listHeader="LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.patient.label" />
				
                                            <column type="renderlet:DATE" name="beratungsdatum" listHeader="LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.dateberatung.label" >
					<data>
						<datetime format="%d-%m-%Y" />
					</data>
				</column>

                                    <column type="renderlet:BUTTON" name="btn-del"  listHeader=""  class="delete">
                                            <label>LLL:EXT:ameos_formidable/conf/locallang.php:formidable.elements.delete.label</label>
					<onclick
						runat="ajax"
						params="rowData::uid"
						cache="false"
						exec="cb1.btnDelete_click()"
					/>
                                    </column>

			</columns>
		</renderlet:LISTER>
                  

	</elements>

</formidable>

**Comment by hannesbochmann** [comment]
Could you please set the extension configuration of rn_base for verbose mayday to true? After this you should see a more verbose error message in place.
Furthermore it would be helpful to install a devlog extension like [mklog](https://github.com/DMKEBUSINESSGMBH/typo3-mklog/) if that doesn't help.

**Comment by AntonMezger** [comment]
Hi,

 

I got the following backtrace, but it seems that actually I do not understand where the problem is coming from. I hope you can help me:

 

 

UNCAUGHT EXCEPTION FOR VIEW: tx_mkforms_action_FormBase
CODE: 1
MESSAGE: PHP Warning: array_key_exists() expects parameter 2 to be array, null given in C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\widgets\searchform\class.tx_mkforms_widgets_searchform_Main.php line 173
STACK: 

TYPO3\CMS\Core\Error\Exception: PHP Warning: array_key_exists() expects parameter 2 to be array, null given in C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\widgets\searchform\class.tx_mkforms_widgets_searchform_Main.php line 173 in C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\core\Classes\Error\ErrorHandler.php:111

Stack trace:

#0 [internal function]: TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'array_key_exist...', 'C:\\inetpub\\wwwr...', 173, Array)

#1 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\widgets\searchform\class.tx_mkforms_widgets_searchform_Main.php(173): array_key_exists('rdt_lister', NULL)

#2 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\widgets\searchform\class.tx_mkforms_widgets_searchform_Main.php(67): tx_mkforms_widgets_searchform_Main->_initCriterias()

#3 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\widgets\searchform\class.tx_mkforms_widgets_searchform_Main.php(24): tx_mkforms_widgets_searchform_Main->_initData()

#4 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\api\class.mainrenderlet.php(524): tx_mkforms_widgets_searchform_Main->_render()

#5 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\api\class.tx_ameosformidable.php(2901): formidable_mainrenderlet->render()

#6 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\api\class.tx_ameosformidable.php(2878): tx_ameosformidable->_renderElement(Object(tx_mkforms_widgets_searchform_Main))

#7 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\api\class.tx_ameosformidable.php(2441): tx_ameosformidable->_renderElements()

#8 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\api\class.tx_ameosformidable.php(2192): tx_ameosformidable->_render()

#9 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\mkforms\action\class.tx_mkforms_action_FormBase.php(113): tx_ameosformidable->render()

#10 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\rn_base\action\class.tx_rnbase_action_BaseIOC.php(87): tx_mkforms_action_FormBase->handleRequest(Object(tx_rnbase_parameters), Object(Tx_Rnbase_Configuration_Processor), Object(ArrayObject))

#11 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\rn_base\class.tx_rnbase_controller.php(254): tx_rnbase_action_BaseIOC->execute(Object(tx_rnbase_parameters), Object(Tx_Rnbase_Configuration_Processor))

#12 C:\inetpub\wwwroot\sdgziel\typo3conf\ext\rn_base\class.tx_rnbase_controller.php(228): tx_rnbase_controller->doAction('tx_mkforms_acti...', Object(tx_rnbase_parameters), Object(Tx_Rnbase_Configuration_Processor))

#13 [internal function]: tx_rnbase_controller->main('', Array)

#14 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\ContentObject\ContentObjectRenderer.php(7322): call_user_func_array(Array, Array)

#15 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\ContentObject\UserContentObject.php(40): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->callUserFunction('tx_rnbase_contr...', Array, '')

#16 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\ContentObject\ContentObjectRenderer.php(943): TYPO3\CMS\Frontend\ContentObject\UserContentObject->render(Array)

#17 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\ContentObject\ContentObjectRenderer.php(859): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render(Object(TYPO3\CMS\Frontend\ContentObject\UserContentObject), Array)

#18 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\Controller\TypoScriptFrontendController.php(3577): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle('USER', Array)

#19 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\Controller\TypoScriptFrontendController.php(3522): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript_process(Array)

#20 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\Controller\TypoScriptFrontendController.php(3488): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()

#21 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\Http\RequestHandler.php(232): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript()

#22 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\core\Classes\Core\Bootstrap.php(308): TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))

#23 C:\inetpub\wwwroot\typo3_src-7.6.31\typo3\sysext\frontend\Classes\Http\Application.php(78): TYPO3\CMS\Core\Core\Bootstrap->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))

#24 C:\inetpub\wwwroot\typo3_src-7.6.31\index.php(33): TYPO3\CMS\Frontend\Http\Application->run()

#25 C:\inetpub\wwwroot\typo3_src-7.6.31\index.php(34): {closure}()

#26 {main}

 

 

 

Best regards

 

Anton

 

De : Hannes Bochmann <notifications@github.com> 
Envoyé : lundi 20 août 2018 08:49
À : DMKEBUSINESSGMBH/typo3-mkforms <typo3-mkforms@noreply.github.com>
Cc : Anton Mezger <antonmezger@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [DMKEBUSINESSGMBH/typo3-mkforms] SearchForm does not work (example below with cut and paste) (#87)

 

Could you please set the extension configuration of rn_base for verbose mayday to true? After this you should see a more verbose error message in place.
Furthermore it would be helpful to install a devlog extension like mklog <https://github.com/DMKEBUSINESSGMBH/typo3-mklog/>  if that doesn't help.

**Comment by AntonMezger** [comment]
Hi,

 

Effectively $GLOBALS['_SESSION'] is null; how to invoke the initializeSessionArray, that method being private?

 

Many thanks for helping me out

 

Best regards

 

 

De : Hannes Bochmann <notifications@github.com> 
Envoyé : lundi 20 août 2018 09:24
À : DMKEBUSINESSGMBH/typo3-mkforms <typo3-mkforms@noreply.github.com>
Cc : Anton Mezger <antonmezger@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [DMKEBUSINESSGMBH/typo3-mkforms] SearchForm does not work (example below with cut and paste) (#87)

 

There seems to be a problem with session handling as $GLOBALS['_SESSION']['ameos_formidable']['applicationdata'] is no array. Could you please check if tx_mkforms_session_MixedSessionManager::initializeSessionArray() is invoked before the error occurs and what's the content of $GLOBALS['_SESSION']['ameos_formidable'] at the start and the end of this method?
You could also check if the problem occurs with older versions of mkforms. After 3.0.14 there were some changes to the session handling. Maybe it works 3.0.14 which would lead us in the right direction.

**Comment by AntonMezger** [comment]
Hi,

 

By the way I use version 3.0.21. I prefer not to go back to an older version, while the problem will occur than again in the future.

 

Best regards

 

Anton

 

De : Hannes Bochmann <notifications@github.com> 
Envoyé : lundi 20 août 2018 09:24
À : DMKEBUSINESSGMBH/typo3-mkforms <typo3-mkforms@noreply.github.com>
Cc : Anton Mezger <antonmezger@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [DMKEBUSINESSGMBH/typo3-mkforms] SearchForm does not work (example below with cut and paste) (#87)

 

There seems to be a problem with session handling as $GLOBALS['_SESSION']['ameos_formidable']['applicationdata'] is no array. Could you please check if tx_mkforms_session_MixedSessionManager::initializeSessionArray() is invoked before the error occurs and what's the content of $GLOBALS['_SESSION']['ameos_formidable'] at the start and the end of this method?
You could also check if the problem occurs with older versions of mkforms. After 3.0.14 there were some changes to the session handling. Maybe it works 3.0.14 which would lead us in the right direction.

**Comment by hannesbochmann** [comment]
You don't need to invoke that method, mkforms should take care of that. It's done for example when tx_mkforms_session_MixedSessionManager is instantiated (check the constrcutor).
You should only go back to an older version to check at which point the functionality broke. My guess is that it will work with mkforms 3.0.14. With that in mind it would be much more easy to track down the problem.

**Comment by hannesbochmann** [comment]
The new error is due to an error in your xml. The <template> configuration of your SEARCHFORM renderlet should be outside the <childs> node.
As I thought the changes after version 3.0.14 introduced this bug. But I'm afraid we don't have time to investigate and fix it right now. Are you willing to dig deeper and provide a pull request?

**Comment by AntonMezger** [comment]
Many thanks,

 

I am going away for holidays and I will try to look at it later. Many thanks, I think I will see to it later. However what means your remark “the renderlet should be outside the node”?

 

Best regards

 

Anton

 

De : Hannes Bochmann <notifications@github.com> 
Envoyé : lundi 20 août 2018 10:26
À : DMKEBUSINESSGMBH/typo3-mkforms <typo3-mkforms@noreply.github.com>
Cc : Anton Mezger <antonmezger@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [DMKEBUSINESSGMBH/typo3-mkforms] SearchForm does not work (example below with cut and paste) (#87)

 

The new error is due to an error in your xml. The configuration of your SEARCHFORM renderlet should be outside the node.
As I thought the changes after version 3.0.14 introduced this bug. But I'm afraid we don't have time to investigate and fix it right now. Are you willing to dig deeper and provide a pull request?

**Comment by hannesbochmann** [comment]
Sorry, I misunderstood something. Your XML structure seems to be fine. But you need to configure thwe <subpart> property for the <template> property of your searchform renderlet like this:
<template>
    <path>fileadmin/xml/template/form_search.html</path>
    <subpart>SEARCH_FORM_RENDERLET</subpart>
</template>

Maybe you need to wrap the subpart with "###" like ###SEARCH_FORM_RENDERLET###. I don't know at the moment. Of course you need the supply this subpart in your template as well.

**Comment by AntonMezger** [comment]
Hi,

 

It works now ; It seems that before the subpart had not to be mentioned while it tool the subpart from the name of the searchform; now it has to be explicitly mentioned.

 

Thanks a lot. 

 

A subsidiary question: is there a replacement for the old extension ameos_feuser_mgr, we are using now?

 

Best regards

 

Anton

 

De : Hannes Bochmann <notifications@github.com> 
Envoyé : lundi 20 août 2018 10:47
À : DMKEBUSINESSGMBH/typo3-mkforms <typo3-mkforms@noreply.github.com>
Cc : Anton Mezger <antonmezger@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [DMKEBUSINESSGMBH/typo3-mkforms] SearchForm does not work (example below with cut and paste) (#87)

 

Sorry, I misunderstood something. Your XML structure seems to be fine. But you need to configure thwe property for the property of your searchform renderlet like this:

fileadmin/xml/template/form_search.html
SEARCH_FORM_RENDERLET

Maybe you need to wrap the subpart with "###" like ###SEARCH_FORM_RENDERLET###. I don't know at the moment. Of course you need the supply this subpart in your template as well.

**Comment by hannesbochmann** [comment]
Considering ameos_feuser_mgr I can't help you with an advice.

**Comment by AntonMezger** [comment]
search form is rendered

**Comment by digedag** [comment]
According to comments in #100 the problem still exists in current head. So I reopen this ticket.

**Comment by digedag** [comment]
Hey @AntonMezger ,
I tried to install the form xml from ticket description. This fails for some missing code behind and html templates. Also a database query to `mytable` isn't possible.

So I stripped down your example and got the search form visible. This works and `$GLOBALS['_SESSION']['ameos_formidable']['applicationdata']` is filled. There is also no error when I click at **Senden**. The session data is filled as expected.
So maybe the problem is related to your custom php code.

It would be really helpful if you could provide a (not) working xml example.

**Comment by AntonMezger** [comment]
Hi,

I patched the version 3.0.14 with your date modifications. I had also to change some protected functions back to public ones. Everything works perfectly well, so that I am currently happy.

I also tried the latest version from git and there is no way to have search forms working. Many different  weird errors. I use php version 7.1

I will keep for the time being the patched version 3.0.14

Best regards

Anton
